const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Behaviors.Anchor,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Plugins.TextBox,
		C3.Plugins.Gritsenko_Spine,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Behaviors.Timer,
		C3.Behaviors.destroy,
		C3.Behaviors.Platform,
		C3.Behaviors.Bullet,
		C3.Behaviors.MoveTo,
		C3.Behaviors.LOS,
		C3.Behaviors.Follow,
		C3.Plugins.Particles,
		C3.Plugins.Spritefont2,
		C3.Behaviors.TR_AnimatedCounter,
		C3.Plugins.Touch,
		C3.Plugins.Json,
		C3.Plugins.AJAX,
		C3.Plugins.yagames_sdk,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.yagames_sdk.Acts.LoadingAPIReady,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.yagames_sdk.Acts.PlayerGetData,
		C3.Plugins.yagames_sdk.Acts.PlayerInfoFetch,
		C3.Plugins.yagames_sdk.Acts.PurchasesFetch,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.yagames_sdk.Cnds.OnPlayerInfoFetchSuccess,
		C3.Plugins.TextBox.Acts.AppendText,
		C3.Plugins.yagames_sdk.Cnds.CurrentPlayerInfoAccessGranted,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.yagames_sdk.Exps.PlayerAvatarLarge,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.yagames_sdk.Cnds.CurrentPlayerIsAuthorized,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.yagames_sdk.Cnds.OnPlayerInfoFetchError,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Json.Cnds.OnParseSuccess,
		C3.Plugins.LocalStorage.Cnds.OnItemSet,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.yagames_sdk.Acts.CatalogFetch,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.yagames_sdk.Cnds.OnCatalogFetchSuccess,
		C3.Plugins.yagames_sdk.Cnds.ForEachInCatalog,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.yagames_sdk.Exps.CurrentCatalogProductID,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.yagames_sdk.Exps.ProductPrice,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.yagames_sdk.Acts.PlayerSetData,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Json.Exps.ToBeautifiedString,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.yagames_sdk.Acts.HideStickyBanner,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Json.Acts.AddTo,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Gritsenko_Spine.Acts.CreateCustomSkin,
		C3.Plugins.Gritsenko_Spine.Acts.AddCustomSkin,
		C3.Plugins.Gritsenko_Spine.Acts.SetCustomSkin,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.yagames_sdk.Cnds.OnPurchasesFetchSuccess,
		C3.Plugins.yagames_sdk.Cnds.ForEachPurchase,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.yagames_sdk.Exps.CurrentPurchasesProductID,
		C3.Plugins.yagames_sdk.Acts.ConsumePurchase,
		C3.Plugins.yagames_sdk.Exps.CurrentPurchaseToken,
		C3.Plugins.yagames_sdk.Cnds.IsDesktop,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.yagames_sdk.Cnds.IsTablet,
		C3.Plugins.yagames_sdk.Cnds.IsMobile,
		C3.Plugins.yagames_sdk.Acts.SetLeaderboardScore,
		C3.Plugins.yagames_sdk.Acts.ShowFullscreenAD,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Gritsenko_Spine.Cnds.OnSkeletonLoaded,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.yagames_sdk.Acts.Purchase,
		C3.Plugins.yagames_sdk.Cnds.OnSpecificPurchaseSuccess,
		C3.Plugins.yagames_sdk.Exps.PurchaseToken,
		C3.Plugins.Gritsenko_Spine.Acts.SetAnimation,
		C3.Plugins.Gritsenko_Spine.Cnds.OnAnimationFinished,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Gritsenko_Spine.Acts.SetSize,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.yagames_sdk.Cnds.OnFullscreenADOpen,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.yagames_sdk.Cnds.OnFullscreenADClose,
		C3.Plugins.yagames_sdk.Cnds.OnFullscreenADError,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.yagames_sdk.Exps.ServerTime,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Json.Acts.SubtractFrom,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Tween.Exps.Value,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Sin.Acts.UpdateInitialState,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Spritefont2.Cnds.CompareOpacity,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.yagames_sdk.Acts.ShowRewardedAD,
		C3.Plugins.yagames_sdk.Cnds.OnRewardedADRewarded,
		C3.Plugins.yagames_sdk.Cnds.OnAnyRewardedADClose,
		C3.Plugins.yagames_sdk.Cnds.OnAnyRewardedADOpen,
		C3.Plugins.yagames_sdk.Cnds.OnAnyRewardedADError,
		C3.Plugins.yagames_sdk.Acts.LeaderboardFetch,
		C3.Plugins.yagames_sdk.Cnds.OnLeaderboardFetchSuccess,
		C3.Plugins.yagames_sdk.Cnds.ForEachInLeaderboard,
		C3.Plugins.yagames_sdk.Exps.GetCurrentLeaderboardEntryScore,
		C3.Plugins.yagames_sdk.Exps.GetCurrentPlayerName,
		C3.Plugins.yagames_sdk.Exps.GetCurrentPlayerAvatar,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.yagames_sdk.Cnds.CanReview,
		C3.Plugins.yagames_sdk.Acts.RequestReview,
		C3.Plugins.yagames_sdk.Cnds.ShortcutCanShowPrompt,
		C3.Plugins.yagames_sdk.Acts.ShortcutShowPrompt,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.SetSteppingMode,
		C3.Plugins.Gritsenko_Spine.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetPreventRotate,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.TR_AnimatedCounter.Acts.AddValue,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Plugins.Gritsenko_Spine.Cnds.IsAnimationPlaying,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Gritsenko_Spine.Acts.SetVisible,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Behaviors.Physics.Acts.RemoveJoints,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Gritsenko_Spine.Acts.SetDefaultColor,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Behaviors.Tween.Acts.SetEnabled,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Json.Exps.GetAsCompactString,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.tokenat,
		C3.Behaviors.TR_AnimatedCounter.Cnds.OnAnimationStarted,
		C3.Behaviors.TR_AnimatedCounter.Cnds.OnAnimationFinished,
		C3.Behaviors.TR_AnimatedCounter.Acts.SetValue,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Gritsenko_Spine.Exps.X,
		C3.Plugins.Gritsenko_Spine.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Gritsenko_Spine.Acts.SetSkin,
		C3.Plugins.Gritsenko_Spine.Acts.SetInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{Твинанимация: 0},
	{"7D": 0},
	{L: 0},
	{Рамки_награда_мини: 0},
	{"7D5": 0},
	{Синусоида: 0},
	{плашка_время: 0},
	{fx_glow_small: 0},
	{Поворот: 0},
	{fx_rotate_line: 0},
	{Title_Ribbon_Icon: 0},
	{UI2025Кадр15: 0},
	{Якорь: 0},
	{врем_7дней: 0},
	{"7_день_скин": 0},
	{SPRATE: 0},
	{PASS: 0},
	{SPRATE3: 0},
	{SPRATE5: 0},
	{SPRATE6: 0},
	{Играть_ui: 0},
	{SPRATE15: 0},
	{SPRATE16: 0},
	{SPRATE17: 0},
	{gg_1: 0},
	{SPRATE20: 0},
	{PoloskaGl: 0},
	{fx_star_white: 0},
	{fx_glow: 0},
	{Разметка_Фон: 0},
	{СледитьЗа: 0},
	{camera_gk_mu: 0},
	{Задание_ui: 0},
	{Колесо_ui: 0},
	{Лидер_борд: 0},
	{Магазин_ui: 0},
	{Назад: 0},
	{Настройки_ui: 0},
	{Спрайт6: 0},
	{Спрайт7: 0},
	{под_прогрес_лвл: 0},
	{Спрайт5: 0},
	{Спрайт8: 0},
	{под_хп: 0},
	{Спрайт10: 0},
	{хп_лвл: 0},
	{Дамой_меню: 0},
	{Спрайт12: 0},
	{Спрайт13: 0},
	{планка_под_монету: 0},
	{UI2025Кадр: 0},
	{UI2025Кадр233: 0},
	{IDS: 0},
	{Вперед_лвл: 0},
	{Спрайт14: 0},
	{Спрайт15: 0},
	{ГЛМЕНЮ_: 0},
	{Переход_загрузка: 0},
	{Переход_макет: 0},
	{Переход_макет2: 0},
	{Конец_фон: 0},
	{Дамой_лвл_конец: 0},
	{Центр_IU: 0},
	{Прогрес_до_босса: 0},
	{Спрайт11: 0},
	{босс_хп: 0},
	{Угасание: 0},
	{под_прогрес_лвл2: 0},
	{шарик_пасс: 0},
	{pass3: 0},
	{галка: 0},
	{pass5: 0},
	{Забрать_пасс: 0},
	{Пасс_полоска: 0},
	{Фон_зад_гл: 0},
	{ФОНЗАДД: 0},
	{Image_CircleGlow_White: 0},
	{Фон_активный: 0},
	{UI2025Кадр4: 0},
	{UI2025Кадр6: 0},
	{Смена_стрелки: 0},
	{UI2025Кадр7: 0},
	{UI2025Кадр9: 0},
	{Купить: 0},
	{Шмот: 0},
	{картачка: 0},
	{Кнопки_креп_игрок: 0},
	{Магазин_выбор: 0},
	{Подсветка: 0},
	{Спрайт18: 0},
	{рамка_скидка: 0},
	{UI2025Кадр3: 0},
	{image_glow_rectangle: 0},
	{Per_1: 0},
	{Per_2: 0},
	{Закрыть_настройки: 0},
	{зз1: 0},
	{зз2: 0},
	{Настройки5: 0},
	{avtolog: 0},
	{Popup_Slide02_Single_Navy_TopGlow: 0},
	{Spraite2: 0},
	{UI2025Кадр10: 0},
	{Image_CircleGlow_White2: 0},
	{ID: 0},
	{GL_Avatar_M: 0},
	{Синусоида2: 0},
	{Gl_m_nlo: 0},
	{UI2025Кадр5: 0},
	{свет_портал: 0},
	{Спрайт3: 0},
	{image_glow_oval_: 0},
	{Замок: 0},
	{затычка_режимы_цвет: 0},
	{Умер_заставка: 0},
	{Креп_кнопки_уп_тф: 0},
	{L_XOD: 0},
	{P_XOD: 0},
	{V_XOD: 0},
	{Y_XOD: 0},
	{UI2025Кадр12: 0},
	{UI2025Кадр13: 0},
	{status_icon_star: 0},
	{Спрайт9: 0},
	{Под_аву: 0},
	{UI2025Кадр14: 0},
	{Рамка_войти: 0},
	{Забрать_задание: 0},
	{Icon_Battle: 0},
	{Выполнено: 0},
	{Доска_задание: 0},
	{Под_полоску_задание: 0},
	{Полоска_задание: 0},
	{Цыкл: 0},
	{UI2025Кадр17: 0},
	{Icon_Adremove: 0},
	{Купить_офф_рекламу: 0},
	{значки_режим: 0},
	{Pictoicon_Arrow_Top: 0},
	{блекс_играть: 0},
	{logs: 0},
	{freeiconlock: 0},
	{удалить: 0},
	{UI2025Кадр16: 0},
	{start_p: 0},
	{start_p2: 0},
	{start_p3: 0},
	{Капилка_п: 0},
	{cvinka_kapilka: 0},
	{Синусоид: 0},
	{Значки_UI4: 0},
	{L2: 0},
	{Box: 0},
	{Icon_Adremove2: 0},
	{SlotRuletka: 0},
	{UI2025Кадр8: 0},
	{Купить2: 0},
	{окно_рулетка: 0},
	{редкость_рулетка: 0},
	{Go: 0},
	{Рулетка_1: 0},
	{Go2: 0},
	{Рулетка_2: 0},
	{Спрайт16: 0},
	{Спрайт17: 0},
	{Спрайт19: 0},
	{Спрайт4: 0},
	{СтикМечиСкиныApp2Кадр: 0},
	{СтикМечиСкиныApp2Кадр2: 0},
	{СтикМечиСкиныApp2Кадр3: 0},
	{СтикМечиСкиныApp2Кадр4: 0},
	{СтикМечиСкиныAppКадр: 0},
	{СтикСкины2Кадр: 0},
	{СтикСкины2Кадр2: 0},
	{Сундуки_гл: 0},
	{UI2025111: 0},
	{UI2025Кадр2: 0},
	{UI: 0},
	{UI2: 0},
	{UI3: 0},
	{UI4: 0},
	{Стрелка_Ук: 0},
	{UI6: 0},
	{Wheel_k: 0},
	{UI9: 0},
	{Цепи: 0},
	{UI11: 0},
	{Основа_колесо: 0},
	{UI14: 0},
	{UI12: 0},
	{Указатель_об: 0},
	{Glow_Cirlce: 0},
	{UI00: 0},
	{UI1: 0},
	{UI5: 0},
	{manis: 0},
	{manis2: 0},
	{Background_ScreenGlow: 0},
	{Image_Effect_Rotate_White: 0},
	{Награда_кол: 0},
	{Награда_кол2: 0},
	{Награда_кол3: 0},
	{Спрайт: 0},
	{Спрайт2: 0},
	{UI7: 0},
	{Background_ScreenGlow2: 0},
	{Background_ScreenGlow3: 0},
	{Pl: 0},
	{Pl2: 0},
	{Pl3: 0},
	{Pl4: 0},
	{Pl5: 0},
	{PlayerAvatar: 0},
	{loading: 0},
	{startY: 0},
	{"9patch": 0},
	{Спрайт17222: 0},
	{Твёрдый: 0},
	{Физика: 0},
	{Блоки: 0},
	{Цветки: 0},
	{МонтажнаяОбласть: 0},
	{МонтажнаяОбласть2: 0},
	{Поршень: 0},
	{Y_: 0},
	{Поршень_лапа: 0},
	{Портал: 0},
	{Лава: 0},
	{МонтажнаяОбласть4: 0},
	{Палка: 0},
	{Палка2: 0},
	{тень_черноя_лвл: 0},
	{фонарь_лвл: 0},
	{Зона_портал: 0},
	{Портал_го: 0},
	{Стенки_доп: 0},
	{звезды: 0},
	{B: 0},
	{Палка3: 0},
	{Отразить_игрока: 0},
	{зона_паука_палка: 0},
	{Блоки_зад_мини: 0},
	{фонарьКадр: 0},
	{AA: 0},
	{DD: 0},
	{UI2025Кадр11: 0},
	{WW: 0},
	{Обучалка_зона: 0},
	{Уничтожить_ПЕРСА: 0},
	{Golova3: 0},
	{Noga5: 0},
	{Noga6: 0},
	{Ruki2: 0},
	{Ruki3: 0},
	{Spina_Verx: 0},
	{Stopa: 0},
	{Stopa2: 0},
	{Noga13: 0},
	{Noga14: 0},
	{Таймер: 0},
	{УничтожениеВнеМакета: 0},
	{Play_sp: 0},
	{Платформер: 0},
	{Пуля: 0},
	{Play: 0},
	{Зона_урона_игрока: 0},
	{физ_игрок: 0},
	{cam: 0},
	{ДвижениеК: 0},
	{NLO: 0},
	{Зона_монеты: 0},
	{Физика_глобал: 0},
	{пет_кардината: 0},
	{МонтажнаяОбласть3: 0},
	{Play_sp_magazin: 0},
	{пет_кардината2: 0},
	{скин_кросы: 0},
	{Q: 0},
	{W: 0},
	{HP: 0},
	{ПолеЗрения: 0},
	{Cvin_z_ps: 0},
	{Cvin_zomb: 0},
	{Kiri4a: 0},
	{Kiri4a_ps: 0},
	{Kriper: 0},
	{Kriper_ps: 0},
	{Pauk: 0},
	{Pauk_Boos: 0},
	{Pauk_Boss_ps: 0},
	{Pauk_ps: 0},
	{Skilet: 0},
	{Skilet_Boos_ps: 0},
	{Skilet_Boss: 0},
	{Skilet_ps: 0},
	{Zombi: 0},
	{zombi_boss: 0},
	{lava_boss: 0},
	{zombi_boss_ps: 0},
	{lava_boss_ps: 0},
	{Zombi_ps: 0},
	{СледоватьЗа: 0},
	{among: 0},
	{krip_Boos_ps: 0},
	{krip_Boss: 0},
	{me4_zoloto: 0},
	{noga: 0},
	{ruka: 0},
	{telo: 0},
	{noga2: 0},
	{ruka2: 0},
	{golova: 0},
	{свин_зомб_урон: 0},
	{golova2: 0},
	{noga3: 0},
	{ruka3: 0},
	{telo2: 0},
	{ruka4: 0},
	{noga4: 0},
	{зомби_урон: 0},
	{golova33: 0},
	{noga011: 0},
	{telo3: 0},
	{noga012: 0},
	{БУМ: 0},
	{golova4: 0},
	{krulo: 0},
	{noga7: 0},
	{telo222: 0},
	{noga8: 0},
	{golova555: 0},
	{he: 0},
	{noga9: 0},
	{popa: 0},
	{noga10: 0},
	{noga11: 0},
	{noga12: 0},
	{паук_урон: 0},
	{golova6: 0},
	{ruka5: 0},
	{luk_00: 0},
	{telo5: 0},
	{ruka6: 0},
	{noga_111: 0},
	{noga_112: 0},
	{стрела: 0},
	{босс_зомб_урон: 0},
	{golova5: 0},
	{ruka_n: 0},
	{ruka_v: 0},
	{telo_boss_zomb: 0},
	{noga_z_v: 0},
	{noga_z_v2: 0},
	{ruka_v2: 0},
	{ruka_n2: 0},
	{удар_бос_зомб: 0},
	{босс_скилет_урон: 0},
	{golova7: 0},
	{ruka7: 0},
	{telo4: 0},
	{ruka8: 0},
	{noga001: 0},
	{noga002: 0},
	{topor: 0},
	{босс_паук_урон: 0},
	{golova8: 0},
	{he2: 0},
	{noga15: 0},
	{popa2: 0},
	{noga16: 0},
	{noga17: 0},
	{noga18: 0},
	{босс_лава_урон: 0},
	{telo_ttk: 0},
	{noga_tts: 0},
	{golova9tt: 0},
	{ruka_n_v: 0},
	{ruka_v_v: 0},
	{noga_tts2: 0},
	{ruka_n_n: 0},
	{ruka_n_n_v: 0},
	{удар_бос_лава: 0},
	{me4_almaz: 0},
	{босс_крипер_урон: 0},
	{ggboss: 0},
	{golova9boss: 0},
	{noga_v_kr: 0},
	{noga_v_kr2: 0},
	{noga_n_kr: 0},
	{noga_n_kr2: 0},
	{gl_ocnova_krip_boss: 0},
	{ggboss3: 0},
	{Блок_награда: 0},
	{Блок_награда4: 0},
	{Блок_награда5: 0},
	{Блок_награда6: 0},
	{Блок_награда7: 0},
	{H: 0},
	{монета: 0},
	{кубки: 0},
	{пассы: 0},
	{tnt_b: 0},
	{tnt_b2: 0},
	{Взрыв: 0},
	{Удар_1_2: 0},
	{удар_молния: 0},
	{Рекошет: 0},
	{tnt_b3: 0},
	{удар_топор: 0},
	{удар_топор2: 0},
	{удар_топор3: 0},
	{Конфети: 0},
	{удар_топор4: 0},
	{AnimatedCounter: 0},
	{Без_Контурный: 0},
	{Text_UI: 0},
	{ID_Tovar: 0},
	{Контурный: 0},
	{Тач: 0},
	{JSON: 0},
	{AJAX: 0},
	{YandexGamesSDK: 0},
	{Клавиатура: 0},
	{ЛокальноеХранилище: 0},
	{Аудио: 0},
	{Браузер: 0},
	{свин_зомб: 0},
	{зомби: 0},
	{скилет_лучник: 0},
	{паук: 0},
	{крипер: 0},
	{курица: 0},
	{Физик_игрок: 0},
	{зомби_босс: 0},
	{скилет_босс: 0},
	{паук_босс: 0},
	{лава_босс: 0},
	{блокс_награда: 0},
	{крипер_босс: 0},
	{Music: 0},
	{Sound: 0},
	{Log: 0},
	{Obloko: 0},
	{Skin_login: 0},
	{YandexTime: 0},
	{TotalTime: 0},
	{sectorCount: 0},
	{winningSector: 0},
	{Index: 0},
	{scroll: 0},
	{scrollC: 0},
	{scrollM: 0},
	{scrollS: 0},
	{ComboNumber: 0},
	{UDAR: 0},
	{HP_Play: 0},
	{Max_HP_BOSS_ZOMB: 0},
	{Max_HP_BOSS_SKILET: 0},
	{Max_HP_BOSS_PAUK: 0},
	{Max_HP_BOSS_LAVA: 0},
	{Max_HP_BOSS_KRIP: 0},
	{Vremens_money: 0},
	{Vremens_pass: 0},
	{Vremens_score: 0},
	{Animation_play: 0},
	{kuda_perexod: 0},
	{Step: 0},
	{skin_me4: 0},
	{skin_hapku: 0},
	{"4vet": 0},
	{VIB: 0},
	{sectorCount2: 0},
	{winningSector2: 0}
];

self.InstanceType = {
	_7D: class extends self.ISpriteInstance {},
	Рамки_награда_мини: class extends self.ISpriteInstance {},
	_7D5: class extends self.ISpriteInstance {},
	плашка_время: class extends self.ISpriteInstance {},
	fx_glow_small: class extends self.ISpriteInstance {},
	fx_rotate_line: class extends self.ISpriteInstance {},
	Title_Ribbon_Icon: class extends self.ISpriteInstance {},
	UI2025Кадр15: class extends self.ISpriteInstance {},
	врем_7дней: class extends self.ISpriteInstance {},
	_7_день_скин: class extends self.ISpriteInstance {},
	SPRATE: class extends self.ISpriteInstance {},
	PASS: class extends self.ISpriteInstance {},
	SPRATE3: class extends self.ISpriteInstance {},
	SPRATE5: class extends self.ISpriteInstance {},
	SPRATE6: class extends self.ISpriteInstance {},
	Играть_ui: class extends self.ISpriteInstance {},
	SPRATE15: class extends self.ISpriteInstance {},
	SPRATE16: class extends self.ISpriteInstance {},
	SPRATE17: class extends self.ISpriteInstance {},
	SPRATE20: class extends self.ISpriteInstance {},
	PoloskaGl: class extends self.ISpriteInstance {},
	fx_star_white: class extends self.ISpriteInstance {},
	fx_glow: class extends self.ISpriteInstance {},
	Разметка_Фон: class extends self.ISpriteInstance {},
	camera_gk_mu: class extends self.ISpriteInstance {},
	Задание_ui: class extends self.ISpriteInstance {},
	Колесо_ui: class extends self.ISpriteInstance {},
	Лидер_борд: class extends self.ISpriteInstance {},
	Магазин_ui: class extends self.ISpriteInstance {},
	Назад: class extends self.ISpriteInstance {},
	Настройки_ui: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	под_прогрес_лвл: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	под_хп: class extends self.ISpriteInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	хп_лвл: class extends self.ISpriteInstance {},
	Дамой_меню: class extends self.ISpriteInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	Спрайт13: class extends self.ISpriteInstance {},
	планка_под_монету: class extends self.ISpriteInstance {},
	UI2025Кадр: class extends self.ISpriteInstance {},
	UI2025Кадр233: class extends self.ISpriteInstance {},
	Вперед_лвл: class extends self.ISpriteInstance {},
	Спрайт14: class extends self.ISpriteInstance {},
	Спрайт15: class extends self.ISpriteInstance {},
	ГЛМЕНЮ_: class extends self.ISpriteInstance {},
	Переход_загрузка: class extends self.ITiledBackgroundInstance {},
	Переход_макет: class extends self.ISpriteInstance {},
	Переход_макет2: class extends self.ISpriteInstance {},
	Конец_фон: class extends self.ISpriteInstance {},
	Дамой_лвл_конец: class extends self.ISpriteInstance {},
	Центр_IU: class extends self.ISpriteInstance {},
	Прогрес_до_босса: class extends self.ISpriteInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	босс_хп: class extends self.ISpriteInstance {},
	под_прогрес_лвл2: class extends self.ISpriteInstance {},
	шарик_пасс: class extends self.ISpriteInstance {},
	pass3: class extends self.ISpriteInstance {},
	галка: class extends self.ISpriteInstance {},
	pass5: class extends self.ISpriteInstance {},
	Забрать_пасс: class extends self.ISpriteInstance {},
	Пасс_полоска: class extends self.ISpriteInstance {},
	Фон_зад_гл: class extends self.ISpriteInstance {},
	ФОНЗАДД: class extends self.ISpriteInstance {},
	Image_CircleGlow_White: class extends self.ISpriteInstance {},
	Фон_активный: class extends self.ITiledBackgroundInstance {},
	UI2025Кадр4: class extends self.ISpriteInstance {},
	UI2025Кадр6: class extends self.ISpriteInstance {},
	Смена_стрелки: class extends self.ISpriteInstance {},
	UI2025Кадр7: class extends self.ISpriteInstance {},
	UI2025Кадр9: class extends self.ISpriteInstance {},
	Купить: class extends self.ISpriteInstance {},
	Шмот: class extends self.ISpriteInstance {},
	картачка: class extends self.ISpriteInstance {},
	Кнопки_креп_игрок: class extends self.ISpriteInstance {},
	Магазин_выбор: class extends self.ISpriteInstance {},
	Подсветка: class extends self.ISpriteInstance {},
	Спрайт18: class extends self.ISpriteInstance {},
	рамка_скидка: class extends self.ISpriteInstance {},
	UI2025Кадр3: class extends self.ISpriteInstance {},
	image_glow_rectangle: class extends self.ISpriteInstance {},
	Per_1: class extends self.ISpriteInstance {},
	Per_2: class extends self.ISpriteInstance {},
	Закрыть_настройки: class extends self.ISpriteInstance {},
	зз1: class extends self.ISpriteInstance {},
	зз2: class extends self.ISpriteInstance {},
	Настройки5: class extends self.ISpriteInstance {},
	avtolog: class extends self.ISpriteInstance {},
	Popup_Slide02_Single_Navy_TopGlow: class extends self.ISpriteInstance {},
	Spraite2: class extends self.ISpriteInstance {},
	UI2025Кадр10: class extends self.ISpriteInstance {},
	Image_CircleGlow_White2: class extends self.ISpriteInstance {},
	GL_Avatar_M: class extends self.ISpriteInstance {},
	Gl_m_nlo: class extends self.ISpriteInstance {},
	UI2025Кадр5: class extends self.ISpriteInstance {},
	свет_портал: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	image_glow_oval_: class extends self.ISpriteInstance {},
	Замок: class extends self.ISpriteInstance {},
	затычка_режимы_цвет: class extends self.ISpriteInstance {},
	Умер_заставка: class extends self.ISpriteInstance {},
	Креп_кнопки_уп_тф: class extends self.ISpriteInstance {},
	L_XOD: class extends self.ISpriteInstance {},
	P_XOD: class extends self.ISpriteInstance {},
	V_XOD: class extends self.ISpriteInstance {},
	Y_XOD: class extends self.ISpriteInstance {},
	UI2025Кадр12: class extends self.ISpriteInstance {},
	UI2025Кадр13: class extends self.ISpriteInstance {},
	status_icon_star: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Под_аву: class extends self.ISpriteInstance {},
	UI2025Кадр14: class extends self.ISpriteInstance {},
	Рамка_войти: class extends self.ISpriteInstance {},
	Забрать_задание: class extends self.ISpriteInstance {},
	Icon_Battle: class extends self.ISpriteInstance {},
	Выполнено: class extends self.ISpriteInstance {},
	Доска_задание: class extends self.ISpriteInstance {},
	Под_полоску_задание: class extends self.ISpriteInstance {},
	Полоска_задание: class extends self.ISpriteInstance {},
	Цыкл: class extends self.ISpriteInstance {},
	UI2025Кадр17: class extends self.ISpriteInstance {},
	Icon_Adremove: class extends self.ISpriteInstance {},
	Купить_офф_рекламу: class extends self.ISpriteInstance {},
	значки_режим: class extends self.ISpriteInstance {},
	Pictoicon_Arrow_Top: class extends self.ISpriteInstance {},
	блекс_играть: class extends self.ISpriteInstance {},
	logs: class extends self.ITextInputInstance {},
	freeiconlock: class extends self.ISpriteInstance {},
	удалить: class extends self.ISpriteInstance {},
	UI2025Кадр16: class extends self.ISpriteInstance {},
	start_p: class extends self.ISpriteInstance {},
	start_p2: class extends self.ISpriteInstance {},
	start_p3: class extends self.ISpriteInstance {},
	Капилка_п: class extends self.ISpriteInstance {},
	cvinka_kapilka: class extends self.IWorldInstance {},
	Значки_UI4: class extends self.ISpriteInstance {},
	Box: class extends self.IWorldInstance {},
	Icon_Adremove2: class extends self.ISpriteInstance {},
	SlotRuletka: class extends self.ISpriteInstance {},
	UI2025Кадр8: class extends self.ISpriteInstance {},
	Купить2: class extends self.ISpriteInstance {},
	окно_рулетка: class extends self.ISpriteInstance {},
	редкость_рулетка: class extends self.ISpriteInstance {},
	Рулетка_1: class extends self.ISpriteInstance {},
	Рулетка_2: class extends self.ISpriteInstance {},
	Спрайт16: class extends self.ISpriteInstance {},
	Спрайт17: class extends self.ISpriteInstance {},
	Спрайт19: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	СтикМечиСкиныApp2Кадр: class extends self.ISpriteInstance {},
	СтикМечиСкиныApp2Кадр2: class extends self.ISpriteInstance {},
	СтикМечиСкиныApp2Кадр3: class extends self.ISpriteInstance {},
	СтикМечиСкиныApp2Кадр4: class extends self.ISpriteInstance {},
	СтикМечиСкиныAppКадр: class extends self.ISpriteInstance {},
	СтикСкины2Кадр: class extends self.ISpriteInstance {},
	СтикСкины2Кадр2: class extends self.ISpriteInstance {},
	Сундуки_гл: class extends self.ISpriteInstance {},
	UI2025111: class extends self.ISpriteInstance {},
	UI2025Кадр2: class extends self.ISpriteInstance {},
	UI: class extends self.ISpriteInstance {},
	UI2: class extends self.ISpriteInstance {},
	UI3: class extends self.ISpriteInstance {},
	UI4: class extends self.ISpriteInstance {},
	Стрелка_Ук: class extends self.ISpriteInstance {},
	UI6: class extends self.ISpriteInstance {},
	Wheel_k: class extends self.ISpriteInstance {},
	UI9: class extends self.ISpriteInstance {},
	Цепи: class extends self.ISpriteInstance {},
	UI11: class extends self.ISpriteInstance {},
	Основа_колесо: class extends self.ISpriteInstance {},
	UI14: class extends self.ISpriteInstance {},
	UI12: class extends self.ISpriteInstance {},
	Указатель_об: class extends self.ISpriteInstance {},
	Glow_Cirlce: class extends self.ISpriteInstance {},
	UI00: class extends self.ISpriteInstance {},
	UI1: class extends self.ISpriteInstance {},
	UI5: class extends self.ISpriteInstance {},
	manis: class extends self.ISpriteInstance {},
	manis2: class extends self.ISpriteInstance {},
	Background_ScreenGlow: class extends self.ISpriteInstance {},
	Image_Effect_Rotate_White: class extends self.ISpriteInstance {},
	Награда_кол: class extends self.ISpriteInstance {},
	Награда_кол2: class extends self.ISpriteInstance {},
	Награда_кол3: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	UI7: class extends self.ISpriteInstance {},
	Background_ScreenGlow2: class extends self.ISpriteInstance {},
	Background_ScreenGlow3: class extends self.ISpriteInstance {},
	Pl: class extends self.ISpriteInstance {},
	Pl2: class extends self.ISpriteInstance {},
	Pl3: class extends self.ISpriteInstance {},
	Pl4: class extends self.ISpriteInstance {},
	Pl5: class extends self.ISpriteInstance {},
	PlayerAvatar: class extends self.ISpriteInstance {},
	loading: class extends self.ISpriteInstance {},
	_9patch: class extends self.ISpriteInstance {},
	Спрайт17222: class extends self.ISpriteInstance {},
	Блоки: class extends self.ITilemapInstance {},
	Цветки: class extends self.ISpriteInstance {},
	МонтажнаяОбласть: class extends self.ISpriteInstance {},
	МонтажнаяОбласть2: class extends self.ISpriteInstance {},
	Поршень: class extends self.ISpriteInstance {},
	Поршень_лапа: class extends self.ISpriteInstance {},
	Портал: class extends self.ISpriteInstance {},
	Лава: class extends self.ISpriteInstance {},
	МонтажнаяОбласть4: class extends self.ISpriteInstance {},
	Палка: class extends self.ITiledBackgroundInstance {},
	Палка2: class extends self.ITiledBackgroundInstance {},
	тень_черноя_лвл: class extends self.ISpriteInstance {},
	фонарь_лвл: class extends self.ISpriteInstance {},
	Зона_портал: class extends self.ISpriteInstance {},
	Портал_го: class extends self.ISpriteInstance {},
	Стенки_доп: class extends self.ISpriteInstance {},
	звезды: class extends self.ITiledBackgroundInstance {},
	Палка3: class extends self.ITiledBackgroundInstance {},
	Отразить_игрока: class extends self.ISpriteInstance {},
	зона_паука_палка: class extends self.ISpriteInstance {},
	Блоки_зад_мини: class extends self.ITilemapInstance {},
	фонарьКадр: class extends self.ISpriteInstance {},
	AA: class extends self.ISpriteInstance {},
	DD: class extends self.ISpriteInstance {},
	UI2025Кадр11: class extends self.ISpriteInstance {},
	WW: class extends self.ISpriteInstance {},
	Обучалка_зона: class extends self.ISpriteInstance {},
	Уничтожить_ПЕРСА: class extends self.ISpriteInstance {},
	Golova3: class extends self.ISpriteInstance {},
	Noga5: class extends self.ISpriteInstance {},
	Noga6: class extends self.ISpriteInstance {},
	Ruki2: class extends self.ISpriteInstance {},
	Ruki3: class extends self.ISpriteInstance {},
	Spina_Verx: class extends self.ISpriteInstance {},
	Stopa: class extends self.ISpriteInstance {},
	Stopa2: class extends self.ISpriteInstance {},
	Noga13: class extends self.ISpriteInstance {},
	Noga14: class extends self.ISpriteInstance {},
	Play_sp: class extends self.IWorldInstance {},
	Play: class extends self.ISpriteInstance {},
	Зона_урона_игрока: class extends self.ISpriteInstance {},
	физ_игрок: class extends self.ISpriteInstance {},
	cam: class extends self.ISpriteInstance {},
	NLO: class extends self.ISpriteInstance {},
	Зона_монеты: class extends self.ISpriteInstance {},
	Физика_глобал: class extends self.ISpriteInstance {},
	пет_кардината: class extends self.ISpriteInstance {},
	МонтажнаяОбласть3: class extends self.ISpriteInstance {},
	Play_sp_magazin: class extends self.IWorldInstance {},
	пет_кардината2: class extends self.ISpriteInstance {},
	скин_кросы: class extends self.ISpriteInstance {},
	Cvin_z_ps: class extends self.ISpriteInstance {},
	Cvin_zomb: class extends self.IWorldInstance {},
	Kiri4a: class extends self.IWorldInstance {},
	Kiri4a_ps: class extends self.ISpriteInstance {},
	Kriper: class extends self.IWorldInstance {},
	Kriper_ps: class extends self.ISpriteInstance {},
	Pauk: class extends self.IWorldInstance {},
	Pauk_Boos: class extends self.IWorldInstance {},
	Pauk_Boss_ps: class extends self.ISpriteInstance {},
	Pauk_ps: class extends self.ISpriteInstance {},
	Skilet: class extends self.IWorldInstance {},
	Skilet_Boos_ps: class extends self.ISpriteInstance {},
	Skilet_Boss: class extends self.IWorldInstance {},
	Skilet_ps: class extends self.ISpriteInstance {},
	Zombi: class extends self.IWorldInstance {},
	zombi_boss: class extends self.IWorldInstance {},
	lava_boss: class extends self.IWorldInstance {},
	zombi_boss_ps: class extends self.ISpriteInstance {},
	lava_boss_ps: class extends self.ISpriteInstance {},
	Zombi_ps: class extends self.ISpriteInstance {},
	among: class extends self.IWorldInstance {},
	krip_Boos_ps: class extends self.ISpriteInstance {},
	krip_Boss: class extends self.IWorldInstance {},
	me4_zoloto: class extends self.ISpriteInstance {},
	noga: class extends self.ISpriteInstance {},
	ruka: class extends self.ISpriteInstance {},
	telo: class extends self.ISpriteInstance {},
	noga2: class extends self.ISpriteInstance {},
	ruka2: class extends self.ISpriteInstance {},
	golova: class extends self.ISpriteInstance {},
	свин_зомб_урон: class extends self.ISpriteInstance {},
	golova2: class extends self.ISpriteInstance {},
	noga3: class extends self.ISpriteInstance {},
	ruka3: class extends self.ISpriteInstance {},
	telo2: class extends self.ISpriteInstance {},
	ruka4: class extends self.ISpriteInstance {},
	noga4: class extends self.ISpriteInstance {},
	зомби_урон: class extends self.ISpriteInstance {},
	golova33: class extends self.ISpriteInstance {},
	noga011: class extends self.ISpriteInstance {},
	telo3: class extends self.ISpriteInstance {},
	noga012: class extends self.ISpriteInstance {},
	БУМ: class extends self.ISpriteInstance {},
	golova4: class extends self.ISpriteInstance {},
	krulo: class extends self.ISpriteInstance {},
	noga7: class extends self.ISpriteInstance {},
	telo222: class extends self.ISpriteInstance {},
	noga8: class extends self.ISpriteInstance {},
	golova555: class extends self.ISpriteInstance {},
	he: class extends self.ISpriteInstance {},
	noga9: class extends self.ISpriteInstance {},
	popa: class extends self.ISpriteInstance {},
	noga10: class extends self.ISpriteInstance {},
	noga11: class extends self.ISpriteInstance {},
	noga12: class extends self.ISpriteInstance {},
	паук_урон: class extends self.ISpriteInstance {},
	golova6: class extends self.ISpriteInstance {},
	ruka5: class extends self.ISpriteInstance {},
	luk_00: class extends self.ISpriteInstance {},
	telo5: class extends self.ISpriteInstance {},
	ruka6: class extends self.ISpriteInstance {},
	noga_111: class extends self.ISpriteInstance {},
	noga_112: class extends self.ISpriteInstance {},
	стрела: class extends self.ISpriteInstance {},
	босс_зомб_урон: class extends self.ISpriteInstance {},
	golova5: class extends self.ISpriteInstance {},
	ruka_n: class extends self.ISpriteInstance {},
	ruka_v: class extends self.ISpriteInstance {},
	telo_boss_zomb: class extends self.ISpriteInstance {},
	noga_z_v: class extends self.ISpriteInstance {},
	noga_z_v2: class extends self.ISpriteInstance {},
	ruka_v2: class extends self.ISpriteInstance {},
	ruka_n2: class extends self.ISpriteInstance {},
	удар_бос_зомб: class extends self.ISpriteInstance {},
	босс_скилет_урон: class extends self.ISpriteInstance {},
	golova7: class extends self.ISpriteInstance {},
	ruka7: class extends self.ISpriteInstance {},
	telo4: class extends self.ISpriteInstance {},
	ruka8: class extends self.ISpriteInstance {},
	noga001: class extends self.ISpriteInstance {},
	noga002: class extends self.ISpriteInstance {},
	topor: class extends self.ISpriteInstance {},
	босс_паук_урон: class extends self.ISpriteInstance {},
	golova8: class extends self.ISpriteInstance {},
	he2: class extends self.ISpriteInstance {},
	noga15: class extends self.ISpriteInstance {},
	popa2: class extends self.ISpriteInstance {},
	noga16: class extends self.ISpriteInstance {},
	noga17: class extends self.ISpriteInstance {},
	noga18: class extends self.ISpriteInstance {},
	босс_лава_урон: class extends self.ISpriteInstance {},
	telo_ttk: class extends self.ISpriteInstance {},
	noga_tts: class extends self.ISpriteInstance {},
	golova9tt: class extends self.ISpriteInstance {},
	ruka_n_v: class extends self.ISpriteInstance {},
	ruka_v_v: class extends self.ISpriteInstance {},
	noga_tts2: class extends self.ISpriteInstance {},
	ruka_n_n: class extends self.ISpriteInstance {},
	ruka_n_n_v: class extends self.ISpriteInstance {},
	удар_бос_лава: class extends self.ISpriteInstance {},
	me4_almaz: class extends self.ISpriteInstance {},
	босс_крипер_урон: class extends self.ISpriteInstance {},
	ggboss: class extends self.ISpriteInstance {},
	golova9boss: class extends self.ISpriteInstance {},
	noga_v_kr: class extends self.ISpriteInstance {},
	noga_v_kr2: class extends self.ISpriteInstance {},
	noga_n_kr: class extends self.ISpriteInstance {},
	noga_n_kr2: class extends self.ISpriteInstance {},
	gl_ocnova_krip_boss: class extends self.ISpriteInstance {},
	ggboss3: class extends self.ISpriteInstance {},
	Блок_награда: class extends self.ISpriteInstance {},
	Блок_награда4: class extends self.ISpriteInstance {},
	Блок_награда5: class extends self.ISpriteInstance {},
	Блок_награда6: class extends self.ISpriteInstance {},
	Блок_награда7: class extends self.ISpriteInstance {},
	монета: class extends self.ISpriteInstance {},
	кубки: class extends self.ISpriteInstance {},
	пассы: class extends self.ISpriteInstance {},
	tnt_b: class extends self.IParticlesInstance {},
	tnt_b2: class extends self.IParticlesInstance {},
	Взрыв: class extends self.ISpriteInstance {},
	Удар_1_2: class extends self.ISpriteInstance {},
	удар_молния: class extends self.ISpriteInstance {},
	Рекошет: class extends self.ISpriteInstance {},
	tnt_b3: class extends self.IParticlesInstance {},
	удар_топор: class extends self.ISpriteInstance {},
	удар_топор2: class extends self.ISpriteInstance {},
	удар_топор3: class extends self.ISpriteInstance {},
	Конфети: class extends self.IWorldInstance {},
	удар_топор4: class extends self.ISpriteInstance {},
	Без_Контурный: class extends self.ISpriteFontInstance {},
	Контурный: class extends self.ISpriteFontInstance {},
	Тач: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	AJAX: class extends self.IInstance {},
	YandexGamesSDK: class extends C3.Plugins.yagames_sdk.Instance {},
	Клавиатура: class extends self.IInstance {},
	ЛокальноеХранилище: class extends self.IInstance {},
	Аудио: class extends self.IInstance {},
	Браузер: class extends self.IInstance {},
	свин_зомб: class extends self.ISpriteInstance {},
	зомби: class extends self.ISpriteInstance {},
	скилет_лучник: class extends self.ISpriteInstance {},
	паук: class extends self.ISpriteInstance {},
	крипер: class extends self.ISpriteInstance {},
	курица: class extends self.ISpriteInstance {},
	Физик_игрок: class extends self.ISpriteInstance {},
	зомби_босс: class extends self.ISpriteInstance {},
	скилет_босс: class extends self.ISpriteInstance {},
	паук_босс: class extends self.ISpriteInstance {},
	лава_босс: class extends self.ISpriteInstance {},
	блокс_награда: class extends self.ISpriteInstance {},
	крипер_босс: class extends self.ISpriteInstance {}
}